### ISSUE TITLE
what to fill "terraform.tfvars"

### ISSUE THREAD

**Issue by hitbear518** [Eximchain/terraform-aws-eximchain-node#9]
![image](https://user-images.githubusercontent.com/5070531/49421209-dcd16e00-f7c9-11e8-9192-1f7cb9201695.png)

I'm confused about docs of "Launch Network with Terraform"

what should be filled with "public_key_path", should I create a new ssh key pair?
what about cert_owner? In realme it is said to be replaced by "USERNAME", I don't quite understand what is that "USERNAME"

**Comment by Lsquared13** [comment]
`public_key_path` should be the public key generated in ["Generate SSH Key for EC2 Instances"](https://github.com/Eximchain/terraform-aws-eximchain-node#generate-ssh-key-for-ec2-instances). If you followed that part of the readme verbatim, the default value should work for you.

`cert_owner` is your current username according to your operating system. Assuming you're on OS X or Linux, you should just be able to use the value `$USER` and let the shell fill it in for you.

Thanks, please post an update to this issue if you have further questions and close the issue if this resolves it to your satisfaction.

**Comment by hitbear518** [comment]
![image](https://user-images.githubusercontent.com/5070531/49423168-6df81300-f7d1-11e8-8721-61b306380c8f.png)

So after filled in the tfvars, I continue the instruction.
but now I stucked with terraform apply after init

![image](https://user-images.githubusercontent.com/5070531/49423194-9122c280-f7d1-11e8-9557-b9711f34ebf1.png)

According to the error, I do not have  ~/.ssh/eximchain-node.pub, but actually I do, see the ls

**Comment by Lsquared13** [comment]
Due to a terraform limitation, the path variable cannot interpolate the `~`. You need to use the full path: `/Users/sen/.ssh/eximchain-node.pub`. I've also made some minor updates to the repository based on your feedback.

Please let me know if you continue to have issues

**Comment by hitbear518** [comment]
I've successfully built and run the node🍺,Can you also tell me what are the suggested aws ec2 specifications? Like what cpu and ram are required to run exim node properly? is default t2.medium OK?
And for blockchain data, how many GBs hard drive space is needed?

**Comment by Lsquared13** [comment]
The `t2.medium` instances are fine for experimenting and testing, but the version of geth currently in use is known to have memory spikes up to ~8 GB. We recommend at least 16 GB RAM for any sort of production use. We currently use `m4.xlarge` instances for the main network.

The chain data currently takes 4.2 GB and will grow over time. Our main network instances are currently using around 16 GB of space. I'd suggest 20 GB as an absolute minimum amount of storage and would probably recommend 50 GB, possibly more for infrastructure you intend to be long-running. Ultimately, it's up to you how much you are willing to overprovision.

**Comment by Lsquared13** [comment]
This issue hasn't been updated in a few days and it looks like your problems are resolved. I am closing this issue. Please don't hesitate to reopen this issue or post another one if you have any further questions.
